### ISSUE TITLE
Pedigree data

### ISSUE THREAD

**Issue by MatsDahlberg** [robinandeer/scout#156]
Pedigree-data kommer nu i en separat yaml-fil. Den kan innehålla lite olika data beroende av vilken data som kliniken har gett.

Är det ok om jag bara gör en yaml->json konvertering och skickar den till dig? Det blir väldigt mycket parsing för att försöka pressa in den i en mysql-tabell.

```

---
1:
  1-1-3A:
    CMMSID:
      - 09-11145
    CMMS_SeqID:
      - WES1
    Capture_date:
      - Na
    Capture_kit:
      - Nimblegen_SeqCapEZExome.V2
    Capture_personnel:
      - Na
    Clinical_db:
      - dbIEM.v1.1.txt
    Clustering_date:
      - Na
    FamilyID:
      - 1
    Father:
      - 1-2-1U
    Inheritance_model:
      - AR
      - AR_compound
      - AD_denovo
      - X
      - X_denovo
    Isolation_date:
      - Unknown
    Isolation_kit:
      - Qiagen Mini
    Isolation_personnel:
      - Unknown
    Medical_doctor:
      - Na
    Mother:
      - 1-2-2U
    Phenotype:
      - 2
    Phenotype_terms:
      - Na
    SampleID:
      - 1-1-3A
    SciLifeID:
      - M.Bjursell_10_01
    Sequencing_kit:
      - Na
    Sex:
      - 1
    Tissue_origin:
      - Fibroblasts
  1-1-4A:
    CMMSID:
      - 09-11146
    CMMS_SeqID:
      - WES1
    Capture_date:
      - Na
    Capture_kit:
      - Nimblegen_SeqCapEZExome.V2
    Capture_personnel:
      - Na
```

Om jag använder

```
json.dumps(load_all(yamlFile), indent=4, sort_keys=True)
```

så blir det:

```
{
    "1": {
        "1-1-3A": {
            "CMMSID": [
                "09-11145"
            ], 
            "CMMS_SeqID": [
                "WES1"
            ], 
            "Capture_date": [
                "Na"
            ], 
            "Capture_kit": [
                "Nimblegen_SeqCapEZExome.V2"
            ], 
            "Capture_personnel": [
                "Na"
            ], 
            "Clinical_db": [
                "dbIEM.v1.1.txt"
            ], 
            "Clustering_date": [
                "Na"
            ], 
            "FamilyID": [
                1
            ], 
            "Father": [
                "1-2-1U"
            ], 
            "Inheritance_model": [
                "AR", 
                "AR_compound", 
                "AD_denovo", 
                "X", 
                "X_denovo"
            ], 
            "Isolation_date": [
                "Unknown"
            ], 
            "Isolation_kit": [
                "Qiagen Mini"
            ], 
            "Isolation_personnel": [
                "Unknown"
            ], 
            "Medical_doctor": [
                "Na"
            ], 
            "Mother": [
                "1-2-2U"
            ], 
            "Phenotype": [
                2
            ], 
            "Phenotype_terms": [
                "Na"
            ], 
            "SampleID": [
                "1-1-3A"
            ], 
            "SciLifeID": [
                "M.Bjursell_10_01"
            ], 
            "Sequencing_kit": [
                "Na"
            ], 
            "Sex": [
                1
            ], 
            "Tissue_origin": [
                "Fibroblasts"
            ]
        }, 
        "1-1-4A": {
            "CMMSID": [
                "09-11146"
            ], 
            "CMMS_SeqID": [
                "WES1"
            ], 
            "Capture_date": [
                "Na"
            ], 
            "Capture_kit": [
                "Nimblegen_SeqCapEZExome.V2"
            ], 
            "Capture_personnel": [
                "Na"
            ]
        }
    }
}
```
